// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Obtener_ram() {
  return window['go']['main']['App']['Obtener_ram']();
}
