version: '7.0.5'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: contenedor_mongodb
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db
    ports:
      - "27000:27017"