version: '3.8'

services:

  db:
    build: .
    stdin_open: true
    tty: true
    restart: always
    container_name: contenedor_mysql
    hostname: host-mysql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_PASSWORD: '2110'
      MYSQL_ROOT_PASSWORD: '2110'
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - '3366:3306'
    expose:
      - '3366'
    networks:
      - node-network
  
  frontend:
    depends_on:
      - servergo
    build: ../frontend/proyecto1-app
    volumes:
      - '../frontend/proyecto1-app:/proyecto1-app'
      - 'frontend/proyecto1-app/node_modules'
    ports:
      - "80:3000"
    expose:
      - '80'
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    networks:
      - node-network
    links:
     - servergo

  servergo:
    build: ../backend/
    depends_on:
      - db
    ports:
      - "9000:9000"
    volumes:
      - '../backend/:/server-go'
      - '/backend/server-go'
      - '/proc/ram_so1_1s2024:/server-go/ram_so1_1s2024'
    command: go run hello.go
    networks:
      - node-network
    stdin_open: true
    restart: always
    links:
      - db

networks: 
  node-network:
    driver: bridge 

volumes:
  my-db:
